version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.12
  build:
    commands:
      - make build
  post_build:
    commands:
      - make package-only

artifacts:
  files:
    - app/source.zip
  name: source.zip
